# To be tested
version: "3.7"
services:
    atlassian-jira:
        container_name: atlassianJiraProd

        environment:
            VIRTUAL_HOST: ${HOST:?Missing environment variable see readme}
            VIRTUAL_PORT: 8080
            LETSENCRYPT_HOST: ${HOST:?Missing environment variable see readme}
            ATL_PROXY_NAME: ${HOST:?Missing environment variable see readme}
            ATL_PROXY_PORT: 443
            ATL_TOMCAT_SECURE: 1
            ATL_JDBC_URL: jdbc:postgresql://postgres:5432/{PG_DB-atlassianJiraProd}
            ATL_JDBC_USER: ${PG_USER-atlassianJiraProd}
            ATL_JDBC_PASSWORD: ${PG_PASSWORD:?Missing environment variable see readme}
            ATL_DB_DRIVER: org.postgresql.Driver
            ATL_DB_TYPE: postgres72

            networks:
                - default
                - nginxproxynet

        ports:
            - 8080

    postgres:
        ports:
            - 5432

        container_name: atlassianJiraPostgresqlProd

        environment:
            FORCE_COLOR: 1
            POSTGRES_USER: ${PG_USER-atlassianJiraProd}
            POSTGRES_PASSWORD: ${PG_PASSWORD:?Missing environment variable see readme}
            POSTGRES_DB: {PG_DB-atlassianJiraProd}

networks:
    nginxproxynet:
        name: ${PROXY_NETWORK_NAME-nginxproxynet}
        external: true
