# To be tested
version: "3.7"
services:
    atlassian-jira:
        container_name: atlassianJiraProd

        environment:
            VIRTUAL_HOST: jira.luisbeu.de
            VIRTUAL_PORT: 8080
            LETSENCRYPT_HOST: jira.luisbeu.de
            ATL_PROXY_NAME: jira.luisbeu.de
            ATL_PROXY_PORT: 443
            ATL_TOMCAT_SECURE: 1

            networks:
                - default
                - nginxproxynet

        ports:
            - 8080

    postgres:
        ports:
            - 5432

        container_name: atlassianJiraPostgresqlProd

        environment:
            FORCE_COLOR: 1
            POSTGRES_USER: atlassianJiraProd
            POSTGRES_PASSWORD_FILE: /run/secrets/postgresPassword
            POSTGRES_DB: atlassianJiraProd

secrets:
    postgresPassword:
        external: true

networks:
    nginxproxynet:
        external: true