version: "3.7"
services:
    atlassian-jira:
        container_name: atlassianJiraDev

        environment:
            FORCE_COLOR: 1
            ATL_JDBC_URL: jdbc:postgresql://postgres:5432/atlassianJiraDev
            ATL_JDBC_USER: atlassianJiraDev
            ATL_JDBC_PASSWORD: wv9MvTcGzRSAqfBFhUcat2
            ATL_DB_DRIVER: org.postgresql.Driver
            ATL_DB_TYPE: postgres72

        ports:
            - 8096:8080

    postgres:
        ports:
            - 5432

        container_name: atlassianJiraPostgresqlDev

        environment:
            FORCE_COLOR: 1
            POSTGRES_USER: atlassianJiraDev
            POSTGRES_PASSWORD: wv9MvTcGzRSAqfBFhUcat2
            POSTGRES_DB: atlassianJiraDev